# fly.toml app configuration file generated for an-bot-nts on 2023-08-21T17:22:39+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "an-bot-nts"
primary_region = "sin"
kill_signal = "SIGTERM"
kill_timeout = "2m0s"

[build]
dockerfile = "Dockerfile"

[env]
AUTH_DOMAIN = "an-bot-obj-dect.firebaseapp.com"
MEASUREMENT_ID = "G-LPKDW93STP"
MESSAGING_SENDER_ID = "631283162914"
PORT = "8080"
PROJECT_ID = "an-bot-obj-dect"
STORAGE_BUCKET = "an-bot-obj-dect.appspot.com"

[[services]]
internal_port = 8080
protocol = "tcp"
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0

[services.concurrency]
hard_limit = 5
soft_limit = 3

[[services.ports]]
handlers = ["http"]
port = "80"

[[services.ports]]
handlers = ["tls", "http"]
port = "443"

[[services.tcp_checks]]
interval = 10000
timeout = 2000
